Repository psyho-pw/jormungandr, pull requests merged in 2023-05, with the labels that each got.

#24 feat: add docker configs
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: enhancement

#28 feat: add env file command to package.json
  docker-compose.yml
  package.json
  pnpm-lock.yaml
Labels: enhancement

#29 feat: fix dockerfile
  .fleet/run.json
  .fleet/settings.json
  Dockerfile
Labels: bug

#30 Feature/logging
  src/respond/respond.service.ts
  src/slack/slack.service.ts
Labels: refactor

#31 fix: change update query to raw one due to lack up support for subquery
  src/respond/respond.controller.ts
  src/respond/respond.service.ts
  src/slack/slack.service.ts
Labels: bug

#32 Feature/respond/renew
  src/respond/dto/update-respond.dto.ts
  src/respond/respond.module.ts
  src/respond/respond.service.ts
  src/slack/slack.service.ts
  src/team/dto/update-team.dto.ts
  src/team/team.module.ts
  src/team/team.service.ts
Labels: enhancement
